package com.ssmweb.mapper;

import com.ssmweb.pojo.EpcpVideoAlarm;
import com.ssmweb.pojo.EpcpVideoAlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EpcpVideoAlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int countByExample(EpcpVideoAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int deleteByExample(EpcpVideoAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int insert(EpcpVideoAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int insertSelective(EpcpVideoAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    List<EpcpVideoAlarm> selectByExample(EpcpVideoAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    EpcpVideoAlarm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") EpcpVideoAlarm record, @Param("example") EpcpVideoAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int updateByExample(@Param("record") EpcpVideoAlarm record, @Param("example") EpcpVideoAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int updateByPrimaryKeySelective(EpcpVideoAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epcp_video_alarm
     *
     * @mbggenerated Thu Sep 21 16:31:56 CST 2017
     */
    int updateByPrimaryKey(EpcpVideoAlarm record);
}